version: '3.8'

services:
  redis:
    image: redis:7.0.15
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "zoo@123456"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:

