version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zoo@123456
      MYSQL_USER: dumbo
      MYSQL_PASSWORD: zoo@123456
      MYSQL_DATABASE: dumbo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
